import type { NextPage } from "next";

import Head from "next/head";
import Layout from "~/components/Layout";

const Messages: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dev Network | Messages</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main>Messages appear here</main>
      </Layout>
    </>
  );
};

export default Messages;
