import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import Chat from "~/components/Chat";
import Layout from "~/components/Layout";

const UsernameChat: NextPage = () => {
  const router = useRouter();
  const { username } = router.query;

  return (
    <>
      <Head>
        <title>Dev Network | Messages</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="mb-4 mr-8 h-[calc(100vh-10rem)] w-full space-y-2">
          <h2 className="-mt-2 ml-1 hidden text-xl md:block">Your chats</h2>
          <Chat>
            <div>{username}</div>
          </Chat>
        </div>
      </Layout>
    </>
  );
};

export default UsernameChat;
