import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Chat from "~/components/Chat";
import Layout from "~/components/Layout";

const Messages: NextPage = () => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Dev Network | Messages</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="mb-4 mr-8 h-[calc(100vh-10rem)] w-full space-y-2">
          {session && (
            <h2 className="-mt-2 ml-1 hidden text-xl md:block">Your chats</h2>
          )}
          <Chat selectedChat={null} />
        </div>
      </Layout>
    </>
  );
};

export default Messages;
