name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

env:
  DATABASE_URL: "https://fake.com"
  NEXTAUTH_SECRET: "https://fake.com"
  NEXTAUTH_URL: "https://fake.com"
  DISCORD_CLIENT_ID: "https://fake.com"
  DISCORD_CLIENT_SECRET: "https://fake.com"
  GOOGLE_CLIENT_ID: "https://fake.com"
  GOOGLE_CLIENT_SECRET: "https:fake.com"
